// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using To_do_list_Infrastructure.Persistence;

#nullable disable

namespace To_do_list_Infrastructure.Migrations
{
    [DbContext(typeof(To_do_list_DbContext))]
    [Migration("20250511195333_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("To_do_list_Core.Entities.List", b =>
                {
                    b.Property<int>("listId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("updatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("listId");

                    b.ToTable("List", (string)null);
                });

            modelBuilder.Entity("To_do_list_Core.Entities.ListItem", b =>
                {
                    b.Property<int>("listItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("isActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("listId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("listItemId");

                    b.HasIndex("listId");

                    b.ToTable("ListItem", (string)null);
                });

            modelBuilder.Entity("To_do_list_Core.Entities.ListItem", b =>
                {
                    b.HasOne("To_do_list_Core.Entities.List", null)
                        .WithMany("items")
                        .HasForeignKey("listId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("To_do_list_Core.Entities.List", b =>
                {
                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
